services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - .:/code

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - rabbitmq
    volumes:
      - .:/code

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

